
exports.seed = function (knex) {
  return knex('mcqAnswers').del()
    .then(function () {
      return knex('mcqAnswers').insert([
        { aid: 1, qid: 1, answer: 'Undefined' },
        { aid: 2, qid: 1, answer: 'Number' },
        { aid: 3, qid: 1, answer: 'Boolean' },
        { aid: 4, qid: 1, answer: 'Float' },
        { aid: 5, qid: 2, answer: '<script>' },
        { aid: 6, qid: 2, answer: '<head>' },
        { aid: 7, qid: 2, answer: '<meta>' },
        { aid: 8, qid: 2, answer: '<style>' },
        { aid: 9, qid: 3, answer: 'spaces' },
        { aid: 10, qid: 3, answer: 'tabs' },
        { aid: 11, qid: 3, answer: 'newlines' },
        { aid: 12, qid: 3, answer: 'All of the above' },
        { aid: 13, qid: 4, answer: 'Serial' },
        { aid: 14, qid: 4, answer: 'Local' },
        { aid: 15, qid: 4, answer: 'Private' },
        { aid: 16, qid: 4, answer: 'Static' },
        { aid: 17, qid: 5, answer: 'Overloading' },
        { aid: 18, qid: 5, answer: 'Loading' },
        { aid: 19, qid: 5, answer: 'Multiplexing' },
        { aid: 20, qid: 5, answer: 'Duplexing' },
        { aid: 21, qid: 6, answer: 'It contain instance variables' },
        { aid: 22, qid: 6, answer: 'It contain constructors' },
        { aid: 23, qid: 6, answer: 'It may extend another class' },
        { aid: 24, qid: 6, answer: 'All of the above' },
        { aid: 25, qid: 7, answer: 'Adele Goldberg' },
        { aid: 26, qid: 7, answer: 'Dennis Ritchie' },
        { aid: 27, qid: 7, answer: 'Alan Kay' },
        { aid: 28, qid: 7, answer: 'Andrea Ferro' },
        { aid: 29, qid: 8, answer: 'Encapsulation' },
        { aid: 30, qid: 8, answer: 'Polymorphism' },
        { aid: 31, qid: 8, answer: 'Exception' },
        { aid: 32, qid: 8, answer: 'Abstraction' },
        { aid: 33, qid: 9, answer: 'Encapsulation' },
        { aid: 34, qid: 9, answer: 'Polymorphism' },
        { aid: 35, qid: 9, answer: 'Inheritance' },
        { aid: 36, qid: 9, answer: 'Data hiding' },
        { aid: 37, qid: 10, answer: 'EC2' },
        { aid: 38, qid: 10, answer: 'S3' },
        { aid: 39, qid: 10, answer: 'Alexa' },
        { aid: 40, qid: 10, answer: 'CloudFront' },
        { aid: 41, qid: 11, answer: 'Java' },
        { aid: 42, qid: 11, answer: 'C++' },
        { aid: 43, qid: 11, answer: 'Python' },
        { aid: 44, qid: 11, answer: 'Node.js' },
        { aid: 49, qid: 12, answer: '2015' },
        { aid: 50, qid: 12, answer: '2014' },
        { aid: 51, qid: 12, answer: '2016' },
        { aid: 52, qid: 12, answer: '2017' },
        { aid: 53, qid: 13, answer: '.js' },
        { aid: 54, qid: 13, answer: '.node' },
        { aid: 55, qid: 13, answer: '.java' },
        { aid: 56, qid: 13, answer: '.txt' },
        { aid: 57, qid: 14, answer: 'File Service' },
        { aid: 58, qid: 14, answer: 'File System' },
        { aid: 59, qid: 14, answer: 'File Store' },
        { aid: 60, qid: 14, answer: 'File Sharing' },
        { aid: 61, qid: 15, answer: '$ npm install express' },
        { aid: 62, qid: 15, answer: '$ node install express' },
        { aid: 63, qid: 15, answer: '$ install express' },
        { aid: 64, qid: 15, answer: 'None of the above' },
        { aid: 65, qid: 16, answer: 'Javascript' },
        { aid: 66, qid: 16, answer: 'C' },
        { aid: 67, qid: 16, answer: 'C++' },
        { aid: 68, qid: 16, answer: 'All of the above' },
        { aid: 73, qid: 17, answer: 'SQL' },
        { aid: 74, qid: 17, answer: 'XML' },
        { aid: 75, qid: 17, answer: 'JSON' },
        { aid: 76, qid: 17, answer: 'All of the mentioned' },
        { aid: 69, qid: 18, answer: '2000' },
        { aid: 70, qid: 18, answer: '2005' },
        { aid: 71, qid: 18, answer: '2009' },
        { aid: 72, qid: 18, answer: '2011' }
      ]);
    });
};

//This table has the answers for questions. 'answer id' which is 'aid' is the primary key. Answers of a particular question can be find using this table

// aid = PRIMARY KEY
// qid = FOREIGN KEY refering to mcqQuestions(qid)